### ISSUE TITLE
Some confusion...

### ISSUE THREAD

**Issue by zeg-io** [niahmiah/mongoose-uuid#1]
I've completed the installation and base code for a schema using your add-on, however, I'm confused as to the line which begins with "require('...').loadType"

The test code is different than the readme, and either way i'm getting "Cannot find module..."  What am I missing?

**Comment by niahmiah** [comment]
The test is only different because it is testing local files instead of using a module loaded via npm install. The README should be correct.

Please provide more of your error/stack trace. Which module failed to load?
